### ISSUE TITLE
systemlookup installation

### ISSUE THREAD

**Issue by totoroha** [katjahahn/SystemLookup#2] opened 2017-07-18 16:09 UTC
Hi Katjahahn,

I have a problem while trying to install the tool using "pip install systemlookup". My system is using python 2.7.10 and this is the error that i got:

λ pip install systemlookup
Collecting systemlookup
  Using cached systemlookup-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admins\appdata\local\temp\pip-build-tdnvmo\systemlookup\setup.py", line 32, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admin\appdata\local\temp\pip-build-tdnvmo\systemlookup\

Would you please tell me how to fix it?

**Comment by katjahahn** [comment] 2017-07-19 12:41
This should be fixed now. Please try again.

**Comment by totoroha** [comment] 2017-07-19 18:45
Thank Katjahan. The installation problem has been resolved. However this is the output when i run this command:
=========
systemlookup -t name "explorer.exe"
Traceback (most recent call last):
  File "C:\Python27\Scripts\systemlookup-script.py", line 11, in <module>
    load_entry_point('systemlookup==0.0.4', 'console_scripts', 'systemlookup')()
  File "c:\python27\lib\site-packages\systemlookup\systemlookup.py", line 123, in main
    data = syslookup(listnr, args.searchtype, args.searchitem)
  File "c:\python27\lib\site-packages\systemlookup\systemlookup.py", line 96, in syslookup
    return requests.get(base_url + sl_list + "&" + sl_type + "&" + sl_search + "&s=").text
  File "c:\python27\lib\site-packages\requests\api.py", line 60, in get
    return request('get', url, **kwargs)
  File "c:\python27\lib\site-packages\requests\api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by katjahahn** [comment] 2017-07-20 05:59
Works for me, I cannot reproduce this error. Check your internet connection and availability of systemlookup.com

**Comment by katjahahn** [comment] 2017-07-20 06:02
I will be closing this because the original issue has been resolved. Open a new issue if there are more.
Thank you for reporting to me! Very appreciated.

**Closed by katjahahn** 2017-07-20 06:02 UTC
Labels: bug
